In [2]:
import pandas as pd
import os

In [4]:
df = pd.read_csv('../data/DA_regio_solvent.csv')
df

,Unnamed: 0,reaction_idx,uid,substrates,products,xtb_solvent,orca_solvent,reaction_smiles,label,simulation_idx
0,0,0,0,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1,O=C1C(I)=CC2(OCCO2)C2C3C=CC(C3)C12,CH2Cl2,dichloromethane,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1>>O=C1C(I)=CC2(...,1,0.0
1,1,0,1,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1,O=C1C=CC2(OCCO2)C2C3C=CC(C3)C12I,CH2Cl2,dichloromethane,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1>>O=C1C=CC2(OCC...,0,0.0
2,2,8,2,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCC(C=O)C1,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCC(C=O)C1,0,0.0
3,3,8,3,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCCC1C=O,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCCC1C=O,1,0.0
4,4,18,4,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1,COC1=C(OC)C(=O)C2(C)C3C=CC(C3)C2C1=O,Methanol,methanol,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1>>COC1=C(OC...,1,0.0
...,...,...,...,...,...,...,...,...,...,...
471,471,3510,471,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1,N#CC1=C(C#N)C(=O)C2C3C=CC(C3)C2C1=O,Methanol,methanol,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1>>N#CC1=C(C#...,0,0.0
472,472,3798,472,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC=C(C)CC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,1,0.0
473,473,3798,473,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC(C)=CCC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,0,0.0
474,474,3904,474,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1C(C#N)C2,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,1,0.0
475,475,3904,475,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1CC2C#N,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,0,0.0

### Generate txt files with reaction smiles

In [6]:
with open('../data/DA_test_solvent.txt', 'w') as f:
    f.writelines("\n".join(df['reaction_smiles'].values))

In [8]:
lines = []
for reaction, xtb_s, orca_s in zip(
    df["reaction_smiles"].values,
    df["xtb_solvent"].values,
    df["orca_solvent"].values
):
    lines.append(f"{reaction} {xtb_s} {orca_s}")

with open('../data/DA_test_solvent.txt', 'w') as f:
    f.writelines("\n".join(lines))

### create new DataFrame containing only succesfully simulated reactions

In [3]:
success_uids = []
for root, dirs, files in os.walk('../scratch/DA_test_solvent/'):
    if len(root.split('/')) > 3 and root.split('/')[-2] == 'DA_test_solvent':
        if os.path.exists(os.path.join(root, 'reaction.xyz')):
            success_uids.append(int(root.split('/')[-1]))
success_uids = sorted(success_uids)
print(success_uids)

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 115, 116, 117, 118, 119, 120, 121, 123, 125, 127, 128, 129, 130, 131, 132, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 173, 174, 175, 177, 178, 179, 180, 183, 185, 187, 188, 193, 194, 195, 196, 197, 198, 199, 200, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 219, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 244, 245, 246, 248, 249, 250, 251, 254, 255, 256, 258, 259, 260, 261, 264, 266, 267, 269, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 282, 283, 284, 288, 289, 290, 292, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 310, 311, 312, 313, 314, 317, 318, 319, 320, 321, 322, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 337, 339, 340, 344, 345, 346, 347, 349, 353, 354, 355, 356, 357, 360, 362, 363, 364, 367, 368, 369, 370, 371, 372, 373, 374, 376, 377, 379, 380, 381, 382, 383, 384, 385, 386, 391, 392, 393, 394, 395, 396, 399, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 417, 418, 419, 420, 421, 422, 423, 424, 427, 429, 430, 431, 432, 434, 435, 436, 437, 438, 439, 440, 441, 442, 447, 448, 449, 451, 453, 458, 460, 461, 463, 464, 468, 469, 470, 471, 472, 473, 474, 475]

In [5]:
uids_to_keep = []
for reaction_idx in df['reaction_idx'].unique():
    selection = df[df['reaction_idx'] == reaction_idx]
    if len(selection[selection['uid'].isin(success_uids)]) > 1:
        for uid in selection[selection['uid'].isin(success_uids)]['uid']:
            uids_to_keep.append(uid)
            
df = df[df['uid'].isin(uids_to_keep)]
df

,Unnamed: 0,reaction_idx,uid,substrates,products,xtb_solvent,orca_solvent,reaction_smiles,label,simulation_idx
2,2,8,2,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCC(C=O)C1,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCC(C=O)C1,0,0.0
3,3,8,3,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCCC1C=O,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCCC1C=O,1,0.0
4,4,18,4,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1,COC1=C(OC)C(=O)C2(C)C3C=CC(C3)C2C1=O,Methanol,methanol,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1>>COC1=C(OC...,1,0.0
5,5,18,5,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1,COC12C(=O)C=C(C)C(=O)C1(OC)C1C=CC2C1,Methanol,methanol,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1>>COC12C(=O...,0,0.0
6,6,33,6,C=C(C)C=O.C=CC(=C)C,CC1=CCCC(C)(C=O)C1,CHCl3,chloroform,C=C(C)C=O.C=CC(=C)C>>CC1=CCCC(C)(C=O)C1,0,0.0
...,...,...,...,...,...,...,...,...,...,...
471,471,3510,471,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1,N#CC1=C(C#N)C(=O)C2C3C=CC(C3)C2C1=O,Methanol,methanol,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1>>N#CC1=C(C#...,0,0.0
472,472,3798,472,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC=C(C)CC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,1,0.0
473,473,3798,473,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC(C)=CCC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,0,0.0
474,474,3904,474,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1C(C#N)C2,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,1,0.0
475,475,3904,475,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1CC2C#N,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,0,0.0

In [6]:
df.to_csv('../data/DA_regio_solvent_success.csv')