In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/DA_regio_solvent.csv')
df

,Unnamed: 0,reaction_idx,uid,substrates,products,xtb_solvent,orca_solvent,reaction_smiles,label,simulation_idx
0,0,0,0,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1,O=C1C(I)=CC2(OCCO2)C2C3C=CC(C3)C12,CH2Cl2,dichloromethane,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1>>O=C1C(I)=CC2(...,1,0.0
1,1,0,1,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1,O=C1C=CC2(OCCO2)C2C3C=CC(C3)C12I,CH2Cl2,dichloromethane,O=C1C=CC2(C=C1I)OCCO2.C1=CCC=C1>>O=C1C=CC2(OCC...,0,0.0
2,2,8,2,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCC(C=O)C1,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCC(C=O)C1,0,0.0
3,3,8,3,C=CC=COC(C)=O.C=CC=O,CC(=O)OC1C=CCCC1C=O,Water,water,C=CC=COC(C)=O.C=CC=O>>CC(=O)OC1C=CCCC1C=O,1,0.0
4,4,18,4,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1,COC1=C(OC)C(=O)C2(C)C3C=CC(C3)C2C1=O,Methanol,methanol,COC1=C(OC)C(=O)C(C)=CC1=O.C1=CCC=C1>>COC1=C(OC...,1,0.0
...,...,...,...,...,...,...,...,...,...,...
471,471,3510,471,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1,N#CC1=C(C#N)C(=O)C2C3C=CC(C3)C2C1=O,Methanol,methanol,N#CC1=C(C#N)C(=O)C=CC1=O.C1=CCC=C1>>N#CC1=C(C#...,0,0.0
472,472,3798,472,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC=C(C)CC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,1,0.0
473,473,3798,473,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C,COC(=O)C12CC(C)=CCC1C(C)(C)CCC2=O,Ether,diethyl ether,COC(=O)C1=CC(C)(C)CCC1=O.C=CC(=C)C>>COC(=O)C12...,0,0.0
474,474,3904,474,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1C(C#N)C2,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,1,0.0
475,475,3904,475,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N,C#CCC1(C)C(=O)C2(C)C=CC1CC2C#N,Benzene,benzene,C#CCC1(C)C=CC=C(C)C1=O.C=CC#N>>C#CCC1(C)C(=O)C...,0,0.0

In [6]:
with open('../data/DA_test_no_solvent.txt', 'w') as f:
    f.writelines("\n".join(df['reaction_smiles'].values))

In [8]:
lines = []
for reaction, xtb_s, orca_s in zip(
    df["reaction_smiles"].values,
    df["xtb_solvent"].values,
    df["orca_solvent"].values
):
    lines.append(f"{reaction} {xtb_s} {orca_s}")

with open('../data/DA_test_solvent.txt', 'w') as f:
    f.writelines("\n".join(lines))